### ISSUE TITLE
Code errors when Arduino automatically updates to version 2

### ISSUE THREAD

**Issue by kerrsmith** [etherkit/Si5351Arduino#27]
When the Arduino IDE automatically updates to version 2 from version 1 it seems to be getting different code than that which is currently on the master branch on Github. For example one error shows that the following line is included in the src/si5351.h file twice:

enum si5351_pll_input{SI5351_PLL_INPUT_XO, SI5351_PLL_INPUT_CLKIN};

This looks like it is from commit ad6005a1d06559237e254097b2a7e51e49309d43.

In the latest commit ae862003ca332cd10cbabb53af685d8e0d800d7d this has been fixed.

I manually copied the files from Github and overwrote the ones the IDE downloaded and the code now works as expected.

**Comment by NT7S** [comment]
Thanks, yes that was indeed a problem that I caught nearly immediately, but I had to wait for the Arduino Library Manager job to pull in the proper release, which took longer than I expected. It looks like it works now, and the faulty version of the v2 library can be removed manually from the libraries folder manually as well as the ZIP file in the ```.arduino15/staging/libraries``` folder. Sorry about the difficulty there.
