### ISSUE TITLE
Cannot set low frequency clock accurately

### ISSUE THREAD

**Issue by igr75** [etherkit/Si5351Arduino#40]
Hi, 
I just used the example sketch and tried to change the frequency to 10kHz. 

  // Set CLK1 to output 10 kHz
  si5351.set_freq(1000000ULL, SI5351_CLK1); 

The clock I have got was in range of 641kHz.
Does this code support kHz clock generation or there is some issue with the code?
Please advise.
Thanks!
Igor

**Comment by NT7S** [comment]
That should work, so it sounds like a regression got into the latest version of the code. Thank you for the report, I'll check it out.
