### ISSUE TITLE
Wrong output frequency (in a few cases)

### ISSUE THREAD

**Issue by kilatan** [etherkit/Si5351Arduino#6]
Hi,
Using your library I found that in some cases I obtain the wrong output frequency (whereas in all other cases that I tested it is working fine). More specifically, I found that the following two combinations of PLL multiplier and frequency divider gives 75MHz (when it should be 150 MHz and 120 MHz respectively).
I tested this on two independent sets of Arduino + Si5351 clock generator, both times with the same result.
Below the code that I used in both cases.

/* wrong frequency - should be 150 MHz: */
clockgen.setupPLLInt(SI5351_PLL_A, 24);
clockgen.setupMultisynthInt(0, SI5351_PLL_A, SI5351_MULTISYNTH_DIV_4);

/* wrong frequency - should be 120 MHz: */
clockgen.setupPLLInt(SI5351_PLL_A, 24);
clockgen.setupMultisynth(0, SI5351_PLL_A, 5, 0, 1);

**Comment by NT7S** [comment]
Sorry, those method names indicate that it comes from a different library.
