### ISSUE TITLE
Si5351::init does not initialize the ref_freq[] nor  corr[] entries for CLKIN

### ISSUE THREAD

**Issue by conr2286** [etherkit/Si5351Arduino#98]
The ref_freq[] and core[] entries for SI5351_PLL_INPUT_CLKIN are uninitialized by Si5351::init(uint8_t xtal_load_c, uint32_t xo_freq, int32_t corr) nor anywhere else that I found.  Consequently, the use of CLKIN causes pll_calc to divide by 0, the uninitialized ref_freq.

I will propose a workaround later today on a branch resolving the problem in Si5351::init.

JimC, KQ7B
conr2286 at gmail

**Comment by NT7S** [comment]
Fixed by #99
